spring.application.name=tcc

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# InfluxDB
influx.url=${INFLUX_URL}
influx.token=${INFLUX_TOKEN}
influx.bucket=${INFLUX_BUCKET}
influx.org=${INFLUX_ORG}

# Firebase
firebase.credentials.path=${FIREBASE_CREDENTIALS_PATH}